set fallback
set dotenv-load := true
set shell := ["bash", "-euxc", "-o", "pipefail"]

default:
    @{{just_executable()}} --list

py-lint:
  pylint ./control_app/src/ --rcfile .pylintrc

py-test:
  python3 -m pytest ./control_app/src/tests/unit
