[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xayn_infra_lib"
version = "0.0.1"
authors = [{ name = "Xayn Devops", email = "devops@xayn.com" }]
description = "Example"
requires-python = ">=3.7"

dependencies = ["pydantic<2.0.0,>=1.8.2"]
