variable "name" {
  description = "Name of the api"
  type        = string
}

variable "token_name" {
  description = "Name of the authorization token (header)"
  type        = string
  default     = "authorizationToken"
}

variable "stage_name" {
  description = "Name of the API stage"
  type        = string
  default     = "default"
}

variable "log_retention_in_days" {
  description = "Specifies the number of days you want to retain log events that relate to the API gateway"
  type        = number
  default     = 7
}

variable "lambda_authorizer_arn" {
  description = "Specifies the ARN for the lambda function that authorizes that tenant"
  type        = string
}

variable "lambda_authorizer_invoke_arn" {
  description = "Specifies the ARN to invoke the lambda function that authorizes that tenant"
  type        = string
}

variable "nlb_dns_name" {
  description = "The network load balancer that receives the proxied traffic (dns_name)"
  type        = string
}

variable "nlb_vpc_link_id" {
  description = "The load balancer vpc link id that in takes the incoming request (generated by global)"
  type        = string
}

variable "web_acl_arn" {
  description = "The ARN of the web ACL"
  type        = string
  default     = null
}

variable "default_method_throttle_settings" {
  description = "API request burst and rate (rps) limit for all methods, including those that don't require an API key"
  type = object({
    burst_limit = number
    rate_limit  = number
  })
  default = {
    burst_limit = 5
    rate_limit  = 10
  }
}

variable "metrics_enabled_api" {
  description = "Whether to enable dimensions for metrics in the API Gateway"
  type        = bool
  default     = false
}


variable "alarm_http_5xx_error" {
  description = "Alarm for API Gateway HTTP-5XX errors."
  type        = any
  default     = {}
}

variable "alarm_latency" {
  description = "Alarm for API Gateway p90 latency."
  type        = any
  default     = {}
}

variable "alarm_error_rate" {
  description = "Alarm for an increased error rate on the API Gateway."
  type        = any
  default     = {}
}

variable "alarm_latency_by_method" {
  description = "Alarm for API Gateway p90 latency by method and resource."
  type        = any
  default     = {}
}

variable "request_parameters" {
  description = "Request Parameters that can manipuate the request or the Headers being send to the service"
  type        = map(string)
  default = {
    "integration.request.header.X-Xayn-Tenant-Id" = "context.authorizer.principalId"
  }
  # default = {
  #   "integration.request.header.X-Tenant-Id" = "'${var.tenant}'"
  # }
}

variable "tags" {
  description = "Map of tags for the deployment"
  type        = map(string)
  default     = {}
}
