variable "name" {
  description = "Name of the api"
  type        = string
}

variable "token_name" {
  description = "Name of the authorization token (header)"
  type        = string
  default     = "authorizationToken"
}

variable "stage_name" {
  description = "Name of the API stage"
  type        = string
  default     = "default"
}

variable "log_retention_in_days" {
  description = "Specifies the number of days you want to retain log events that relate to the API gateway"
  type        = number
  default     = 7
}

variable "lambda_authorizer_arn" {
  description = "Specifies the ARN for the lambda function that authorizes that tenant"
  type        = string
}

variable "lambda_authorizer_invoke_arn" {
  description = "Specifies the ARN to invoke the lambda function that authorizes that tenant"
  type        = string
}

variable "nlb_dns_name" {
  description = "The network load balancer that receives the proxied traffic (dns_name)"
  type        = string
}

variable "nlb_vpc_link_id" {
  description = "The load balancer vpc link id that in takes the incoming request (generated by global)"
  type        = string
}

variable "web_acl_arn" {
  description = "The ARN of the web ACL"
  type        = string
  default     = null
}

variable "default_method_throttle_settings" {
  description = "API request burst and rate (rps) limit for all methods, including those that don't require an API key"
  type = object({
    burst_limit = number
    rate_limit  = number
  })
  default = {
    burst_limit = 5
    rate_limit  = 10
  }
}

variable "metrics_enabled_api" {
  description = "Whether to enable dimensions for metrics in the API Gateway"
  type        = bool
  default     = false
}

variable "alarm_http_5xx_error" {
  description = "Alarm for API Gateway HTTP-5XX errors."
  type        = any
  default     = {}
}

variable "alarm_latency" {
  description = "Alarm for API Gateway p90 latency."
  type        = any
  default     = {}
}

variable "alarm_error_rate" {
  description = "Alarm for an increased error rate on the API Gateway."
  type        = any
  default     = {}
}

variable "alarm_latency_by_method" {
  description = "Alarm for API Gateway p90 latency by method and resource."
  type        = any
  default     = {}
}

variable "request_parameters" {
  description = "Request Parameters that can manipulate the request or the Headers being send to the service"
  type        = map(string)
  default = {
    "integration.request.header.X-Xayn-Tenant-Id" = "context.authorizer.principalId"
  }
}

variable "provisioning_lambda_role" {
  description = "The role / principal that can call the internal _silo_management_api"
  type        = string
}

variable "enable_access_logs" {
  description = "Enable API access logs"
  type        = bool
  default     = false
}

variable "access_logs_format" {
  description = "API access log format setting"
  type        = map(string)
  default = {
    "requestId"                     = "$context.requestId",
    "waf-error"                     = "$context.waf.error",
    "waf-status"                    = "$context.waf.status",
    "waf-latency"                   = "$context.waf.latency",
    "waf-response"                  = "$context.wafResponseCode",
    "authenticate-error"            = "$context.authenticate.error",
    "authenticate-status"           = "$context.authenticate.status",
    "authenticate-latency"          = "$context.authenticate.latency",
    "authorize-error"               = "$context.authorize.error",
    "authorize-status"              = "$context.authorize.status",
    "authorize-latency"             = "$context.authorize.latency",
    "integration-error"             = "$context.integration.error",
    "integration-status"            = "$context.integration.status",
    "integration-latency"           = "$context.integration.latency",
    "integration-requestId"         = "$context.integration.requestId",
    "integration-integrationStatus" = "$context.integration.integrationStatus",
    "response-latency"              = "$context.responseLatency",
    "status"                        = "$context.status"
  }
}

# Domain Configuration
variable "domain_name" {
  description = "The domain name for the API Gateway"
  type        = string
  default     = null
}

variable "certificate_arn" {
  description = "The ARN of the ACM certificate validated"
  type        = string
  default     = null
}

variable "zone_id" {
  description = "Domain zone ID for where the record is going to be created"
  type        = string
  default     = null
}

variable "tags" {
  description = "Map of tags for the deployment"
  type        = map(string)
  default     = {}
}
