name: All Verifications (PR)

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  terraform:
    name: Verify linting of Terraform files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: xom9ikk/dotenv@eff1dce037c4c0143cc4180a810511024c2560c0 # v2.0.0

      - uses: extractions/setup-just@95b912dc5d3ed106a72907f2f9b91e76d60bdb76 # v1.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          just-version: '${{ env.JUST_VERSION }}'

      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - uses: terraform-linters/setup-tflint@ba6bb2989f94daf58a4cc6eac2c1ca7398a678bf # v3.0.0
        name: Setup TFLint
        with:
          tflint_version: v${{ env.TFLINT_VERSION }}

      - name: Recursive analysis of Terraform files
        run: just tf-fmt-check

      - name: TFLint analysis of Terraform files
        run: just tflint

  python:
    name: Verify Python projects
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: xom9ikk/dotenv@eff1dce037c4c0143cc4180a810511024c2560c0 # v2.0.0

      - uses: extractions/setup-just@95b912dc5d3ed106a72907f2f9b91e76d60bdb76 # v1.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          just-version: '${{ env.JUST_VERSION }}'

      - name: Install dependencies
        working-directory: saas/control_app/src
        run: just py-install

      - name: Run lint
        working-directory: saas/control_app/src
        run: just py-lint

      - name: Run test
        working-directory: saas/control_app/src
        run: just py-test
